### ISSUE TITLE
gemini api ask_stream() calling error

### ISSUE THREAD

**Issue by cpedia** [yym68686/ModelMerge#2]
File "/usr/local/lib/python3.11/site-packages/ModelMerge/models/gemini.py", line 156, in ask_stream
    url = self.api_url.format(model=model or self.engine, stream="streamGenerateContent", api_key=self.api_key)
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'BaseAPI' object has no attribute 'format'

It seems that the api_url is inited as a BaseAPI object but not a Str object.

**Comment by yym68686** [comment]
Hello, thank you for providing the error log. I have now fixed this bug. Upgrading to the latest version of model merge will solve the problem. The upgrade command is:

```bash
pip install -U modelmerge
```

Below is my test script:

```python
import os
from ModelMerge import gemini

api_key = os.getenv("GOOGLE_AI_API_KEY")
engine = "gemini-1.5-flash-exp-0827"

agent = gemini(
    api_key=api_key,
    engine=engine,
    use_plugins=False
)

for i in agent.ask_stream("say test"):
    print(i, end="")
```
