### ISSUE TITLE
the response of typescript or jsx has been escaped.

### ISSUE THREAD

**Issue by cpedia** [yym68686/ModelMerge#3]
![1733995312189](https://github.com/user-attachments/assets/9f36a576-3991-49e8-85e7-759fd23fa88b)

**Comment by cpedia** [comment]
the prompt for testing.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/9e2ff9e6-1350-42b6-b4b7-34968f78fe14" />

**Comment by yym68686** [comment]
Hello, please provide the modelmerge test code, I'm not sure where the bug is.

**Comment by cpedia** [comment]
Please refer to: https://chatgpt.com/share/675bf0d2-0ef0-800d-a5a9-087b465eb8a2

or use steam mode with the following prompts: give me some example code of next.js to build a modern web site

**Comment by cpedia** [comment]
I fixed the issue by decoding the response

content = bytes(content, "utf-8").decode("unicode_escape")

**Comment by yym68686** [comment]
Hello, the latest version has resolved this issue, thank you for the information provided❤️.
